app/task3/blueprint.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from flask_security import login_required
import models 
from app import db
from sqlalchemy import text
from datetime import datetime
import subprocess



task3 = Blueprint('task3', __name__, template_folder='templates')

@task3.route('/task3')
#@login_required
def index():
    return render_template('task3/index.html')

@task3.route('/task3_search', methods=['POST'])
#@login_required
def task3_search():
    user_input = request.get_json().get('name')
    cmd = 'cat' + " " + user_input
    results = subprocess.check_output(cmd, shell=True)
    str_res = str(results).replace("\\n", "\n")
    str_res = str(str_res).replace("b'", " ")
    d = {"info": str_res}
    return jsonify(d)





  




   

   






    

app/task5/blueprint.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from flask_security import login_required
import models 
from app import db
from sqlalchemy import text
from datetime import datetime
from .forms import IsForm



task5 = Blueprint('task5', __name__, template_folder='templates')

@task5.route('/task5')
#@login_required
def index():
    return render_template('task5/index.html')

@task5.route('/task5_search', methods=['POST'])
#@login_required
def task5_search():
    user_input = request.get_json().get('kr_name')
    results = models.iss.query.filter(models.iss.kr_name == user_input).all()
    return jsonify(results)

@task5.route('/task5_create', methods=['POST'])
#@login_required
def task5_create():
    user_input = request.get_json()
    form = IsForm(data=user_input)
    if form.validate():
        task = models.iss(kr_name = form.kr_name.data, name = form.name.data, kategor = form.kategor.data, tip = form.tip.data)
        db.session.add(task)
        db.session.commit()
        return jsonify(task)
    return render_template('task5/index.html')
    





  




   

   






    

app/task6/blueprint.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify, send_file
from flask_security import login_required
import models 
from app import db
from sqlalchemy import text
from datetime import datetime
from wand.image import Image as WandImage
import os
import io



task6 = Blueprint('task6', __name__, template_folder='templates')

@task6.route('/task6')
#@login_required
def index():
    return render_template('task6/index.html')


@task6.route('/upload-photo', methods=['POST'])
def process_image():
   # Получаем файл из запроса
    image_file = request.files['photo']
    
    # Открываем изображение с помощью Wand
    with WandImage(file=image_file) as img:
        # Пример обработки - изменение размера изображения
        img.resize(200, 200)
        
        # Сохраняем обработанное изображение в буфер
        processed_image_buffer = io.BytesIO()
        img.save(file=processed_image_buffer)
        processed_image_buffer.seek(0)  # Перемещаем указатель в начало буфера


    return render_template('task6/index.html')


    





  




   

   






    

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
    <title> {%block title%} {%endblock%} | Axoft </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/fontello.css')}}">
    <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
  </head>
  <body>
    <header>
      <div class="container">
        <div class="row">
          <div class="col-12">
            <h1 class="text-center text-dark">Стенд AXOFT</h1>
            <a class = "btn btn-itd btn-lg text-uppercase" href = "{{url_for('index')}}" role = "button">Главная</a>
          </div>
        </div>
      </div>
    </header>
    {%block main%}   {%endblock%}
    <footer id="footer">
      <div class="container">
        <div class="row">
          <div class="col-12 text-center">
            <a class="btn btn-outline-light" target="_blank" href="#"><i class="icon-mail"></i></a>
            <a class="btn btn-outline-light" target="_blank" href="#"><i class="icon-github-circled-alt"></i></a>
            <a class="btn btn-outline-light" target="_blank" href="#"><i class="icon-paper-plane-empty"></i></a>
          </div>
        </div>
      </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/index.html
{%extends 'base.html'%}

{%block title%}
 Главная страница
{%endblock%}

{%block main%}
<section class="about">
    <div class="container">
        <div class="row">
            <h2 class="text-center text-uppercase color1 mb-5">Примеры уязвимостей</h2>
        </div>
        <div class="row">
            <div class="col-xl-4 col-md-6 col-sm-12">
                <div class="itd_circle"><a class="btn" target="_blank" href="{{url_for('task.index')}}"><i class="icon-buffer"></i></a></div>
                <h5 class="text-center">SQL-инъекции</h5>
                <div class="line"></div>
            </div>
            <div class="col-xl-4 col-md-6 col-sm-12">
              <div class="itd_circle"><a class="btn" target="_blank" href="{{url_for('task6.index')}}"><i class="icon-buffer"></i></a></div>
              <h5 class="text-center">Загрузка файла</h5>
              <div class="line"></div>
          </div>
            <div class="col-xl-4 col-md-6 col-sm-12">
                <div class="itd_circle"><a class="btn" target="_blank" href="{{url_for('task2.index')}}"><i class="icon-eye-off"></i></a></div>
                <h5 class="text-center">XSS-инъекции (Vue.js)</h5>
                <div class="line"></div>
            </div>
            <div class="col-xl-4 col-md-6 col-sm-12">
                <div class="itd_circle"><a class="btn" target="_blank" href="{{url_for('task3.index')}}"><i class="icon-block"></i></a></div>
                <h5 class="text-center">OS-инъекции</h5>
                <div class="line"></div>
            </div>
            <div class="col-xl-4 col-md-6 col-sm-12">
                <div class="itd_circle"><a class="btn" target="_blank" href="{{url_for('task5.index')}}"><i class="icon-eye-off"></i></a></div>
                <h5 class="text-center">XSS-инъекции (JS)</h5>
                <div class="line"></div>
            </div>
            <div class="col-xl-4 col-md-6 col-sm-12">
                <div class="itd_circle"><a class="btn" target="_blank" href="{{url_for('task4.index')}}"><i class="icon-share"></i></a></div>
                <h5 class="text-center">Clickjacking</h5>
                <div class="line"></div>
            </div>
        </div>
    </div>
</section>
<section>
    <div class="container">
        <div class="row">
          <h2 class="text-center text-uppercase color2 mb-5">Наши Возможности</h2>
        </div>
        <div class="row">
            <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-indicators">
                  <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                  <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                  <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
                </div>
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img src="{{ url_for('static', filename='img/05.png') }}" class="d-block w-100" alt="...">
                  </div>
                  <div class="carousel-item">
                    <img src="{{ url_for('static', filename='img/06.png') }}" class="d-block w-100" alt="...">
                  </div>
                  <div class="carousel-item">
                    <img src="{{ url_for('static', filename='img/07.png') }}" class="d-block w-100" alt="...">
                  </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
    </div>
</section>
{%endblock%}